export const shortcuts = {
  createFolder: ["Control", "Shift", "N"],
  uploadFiles: ["Control", "U"],
  cut: ["Control", "X"],
  copy: ["Control", "C"],
  paste: ["Control", "V"],
  rename: ["F2"],
  download: ["Control", "D"],
  delete: ["Delete"],
  selectAll: ["Control", "A"],
  selectIndividuals: ["Control", "Click"],
  selectRange: ["Shift", "Click"],
  selectArrows: ["Shift", "Arrows"],
  navigation: ["Arrows"],
  jumpToFirst: ["Home"],
  jumpToLast: ["End"],
  listLayout: ["Control", "Shift", "1"],
  gridLayout: ["Control", "Shift", "2"],
  refresh: ["F5"],
  clearSelection: ["Escape"],
};
